name: can
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07
  - certifi=2018.10.15
  - libedit=3.1.20170329
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.1.1
  - pip=18.1
  - python=3.6.7
  - readline=7.0
  - setuptools=40.5.0
  - sqlite=3.25.2
  - termcolor=1.1.0
  - tk=8.6.8
  - wheel=0.32.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - canard==0.2.2
    - python-can==3.0.0
    - typing==3.6.6
    - wrapt==1.10.11
